# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dice_by_component": "01_local_interpret.ipynb",
         "plot_rotation_series": "01_local_interpret.ipynb",
         "rotation_series": "01_local_interpret.ipynb",
         "plot_rotation": "01_local_interpret.ipynb",
         "plot_crop_series": "01_local_interpret.ipynb",
         "crop_series": "01_local_interpret.ipynb",
         "plot_crop": "01_local_interpret.ipynb",
         "plot_brightness_series": "01_local_interpret.ipynb",
         "bright_series": "01_local_interpret.ipynb"}

modules = ["core.py"]

doc_url = "https://chfc-cmi.github.io/misas/"

git_url = "https://github.com/chfc-cmi/misas/tree/master/"

def custom_doc_links(name): return None
