# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dice_by_component": "01_local_interpret.ipynb",
         "Fastai1_model": "01_local_interpret.ipynb",
         "default_cmap": "01_local_interpret.ipynb",
         "get_generic_series": "01_local_interpret.ipynb",
         "plot_series": "01_local_interpret.ipynb",
         "plot_frame": "01_local_interpret.ipynb",
         "gif_series": "01_local_interpret.ipynb",
         "eval_generic_series": "01_local_interpret.ipynb",
         "rotationTransform": "01_local_interpret.ipynb",
         "get_rotation_series": "01_local_interpret.ipynb",
         "eval_rotation_series": "01_local_interpret.ipynb",
         "cropTransform": "01_local_interpret.ipynb",
         "get_crop_series": "01_local_interpret.ipynb",
         "eval_crop_series": "01_local_interpret.ipynb",
         "brightnessTransform": "01_local_interpret.ipynb",
         "get_brightness_series": "01_local_interpret.ipynb",
         "eval_bright_series": "01_local_interpret.ipynb",
         "contrastTransform": "01_local_interpret.ipynb",
         "get_contrast_series": "01_local_interpret.ipynb",
         "eval_contrast_series": "01_local_interpret.ipynb",
         "zoomTransform": "01_local_interpret.ipynb",
         "get_zoom_series": "01_local_interpret.ipynb",
         "eval_zoom_series": "01_local_interpret.ipynb",
         "dihedralTransform": "01_local_interpret.ipynb",
         "get_dihedral_series": "01_local_interpret.ipynb",
         "eval_dihedral_series": "01_local_interpret.ipynb",
         "resizeTransform": "01_local_interpret.ipynb",
         "get_resize_series": "01_local_interpret.ipynb",
         "eval_resize_series": "01_local_interpret.ipynb",
         "spikeTransform": "04_mr_artifacts.ipynb",
         "get_spike_series": "04_mr_artifacts.ipynb",
         "eval_spike_series": "04_mr_artifacts.ipynb",
         "biasfieldTransform": "04_mr_artifacts.ipynb",
         "get_biasfield_series": "04_mr_artifacts.ipynb",
         "eval_biasfield_series": "04_mr_artifacts.ipynb"}

modules = ["core.py",
           "mri.py"]

doc_url = "https://chfc-cmi.github.io/misas/"

git_url = "https://github.com/chfc-cmi/misas/tree/master/"

def custom_doc_links(name): return None
