# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://chfc-cmi.github.io/misas/"

git_url = "https://github.com/chfc-cmi/misas/tree/master/"

def custom_doc_links(name): return None
